"""WP-2.3 §3.2/§3.3 — the instance key, the manifest, and ``countersign.py``.

The instance layer's whole justification is DISCLOSURE. ``bench/harness/
commit.py`` generates a signing key when the file is absent, and WP-2.1
recorded that as a defect: it produces a manifest that verifies perfectly under
a fingerprint nobody has ever seen. Generation here is intended — and what
makes it acceptable rather than the same defect is that the event reaches the
artifact. So the disclosure is asserted, not assumed:

* the report prints the fingerprint and states how the key came to exist;
* the manifest records the generation event, the path and the creation time;
* a run that cannot obtain a key writes NOTHING, and that is proven by
  planted-red rather than by reading the code.

``tools/countersign.py`` is exercised through its process entry point, because
that is the surface the operator uses. Its three refusals — absent key, a hash
that is not 64 hex characters, and the benchmark key (D23) — each get a test.
"""

from __future__ import annotations

import hashlib
import json
import os
import stat
import subprocess
import sys
from pathlib import Path

import pytest

from src.discovery.report import Report, ReportMeta, tool_digests
from src.discovery.signing import (
    BENCH_KEY_FINGERPRINT,
    RELEASE_KEY_FINGERPRINT,
    SigningError,
    build_manifest,
    input_digests,
    load_or_create_instance_key,
    manifest_bytes,
    manifest_hash,
    sign_manifest,
)

REPO_ROOT = Path(__file__).resolve().parents[1]
DEMO = REPO_ROOT / "examples" / "demo"
COUNTERSIGN = REPO_ROOT / "tools" / "countersign.py"


def _ed25519_pem(tmp: Path, name: str = "key.pem") -> Path:
    from cryptography.hazmat.primitives import serialization
    from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

    private = Ed25519PrivateKey.generate()
    path = tmp / name
    path.write_bytes(
        private.private_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PrivateFormat.PKCS8,
            encryption_algorithm=serialization.NoEncryption(),
        )
    )
    return path


def _fingerprint_of_pem(path: Path) -> str:
    from cryptography.hazmat.primitives import serialization

    private = serialization.load_pem_private_key(path.read_bytes(), password=None)
    raw = private.public_key().public_bytes(
        encoding=serialization.Encoding.Raw, format=serialization.PublicFormat.Raw
    )
    return hashlib.sha256(raw).hexdigest()[:16]


# --------------------------------------------------------------------------
# The instance key
# --------------------------------------------------------------------------


def test_first_run_generates_a_key_at_the_documented_path(tmp_path) -> None:
    key = load_or_create_instance_key(tmp_path)
    assert key.generated_this_run is True
    assert (tmp_path / ".relian" / "instance-ed25519.pem").is_file()
    assert key.path.endswith("instance-ed25519.pem")


def test_the_generated_key_is_mode_0600(tmp_path) -> None:
    load_or_create_instance_key(tmp_path)
    mode = stat.S_IMODE((tmp_path / ".relian" / "instance-ed25519.pem").stat().st_mode)
    assert mode == 0o600, f"instance key is mode {mode:04o}"


def test_the_second_run_loads_the_same_key_and_says_so(tmp_path) -> None:
    first = load_or_create_instance_key(tmp_path)
    second = load_or_create_instance_key(tmp_path)
    assert second.generated_this_run is False
    assert second.fingerprint == first.fingerprint
    # Same recorded creation time on both runs — otherwise a per-run fact
    # would leak into the signed manifest and two runs would disagree for a
    # reason that has nothing to do with the tree.
    assert second.created_at == first.created_at


def test_the_generation_event_is_recorded_in_the_manifest_block(tmp_path) -> None:
    """The WP-2.1 asymmetry: generation is acceptable BECAUSE it is disclosed."""
    key = load_or_create_instance_key(tmp_path)
    record = key.record()
    assert record["generated_this_run"] is True
    assert record["fingerprint"] == key.fingerprint
    assert record["created_at"] == key.created_at
    assert "generated by Relian on first use" in record["origin"]
    assert "never held by Visionblox" in record["origin"]


def test_a_world_readable_key_is_refused_rather_than_used(tmp_path) -> None:
    load_or_create_instance_key(tmp_path)
    key_path = tmp_path / ".relian" / "instance-ed25519.pem"
    os.chmod(key_path, 0o644)
    with pytest.raises(SigningError, match="readable by someone other than its owner"):
        load_or_create_instance_key(tmp_path)


def test_a_corrupt_key_is_refused_and_never_silently_replaced(tmp_path) -> None:
    """Replacing an unreadable key would change the fingerprint under which
    every previous report was signed, without saying so."""
    load_or_create_instance_key(tmp_path)
    key_path = tmp_path / ".relian" / "instance-ed25519.pem"
    original = key_path.read_bytes()
    key_path.write_bytes(b"-----BEGIN PRIVATE KEY-----\nnot a key\n")
    os.chmod(key_path, 0o600)
    with pytest.raises(SigningError, match="could not be loaded"):
        load_or_create_instance_key(tmp_path)
    assert key_path.read_bytes() != original, "the fixture did not corrupt anything"
    assert key_path.read_bytes().startswith(b"-----BEGIN PRIVATE KEY-----\nnot a key")


def test_a_non_ed25519_key_is_refused(tmp_path) -> None:
    from cryptography.hazmat.primitives import serialization
    from cryptography.hazmat.primitives.asymmetric import rsa

    (tmp_path / ".relian").mkdir()
    key_path = tmp_path / ".relian" / "instance-ed25519.pem"
    private = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    key_path.write_bytes(
        private.private_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PrivateFormat.PKCS8,
            encryption_algorithm=serialization.NoEncryption(),
        )
    )
    os.chmod(key_path, 0o600)
    with pytest.raises(SigningError, match="not an Ed25519 key"):
        load_or_create_instance_key(tmp_path)


def test_a_key_predating_the_creation_record_reports_unknown_not_a_guess(tmp_path) -> None:
    """R1 on a new surface: a creation time this installation cannot know is
    stated as unknown, never fabricated from the file's mtime."""
    load_or_create_instance_key(tmp_path)
    (tmp_path / ".relian" / "instance-key.json").unlink()
    key = load_or_create_instance_key(tmp_path)
    assert key.created_at.startswith("unknown")


def test_key_generation_failure_is_a_hard_stop(tmp_path) -> None:
    """Planted-red for acceptance ④'s sibling: no key, no report."""
    blocked = tmp_path / "blocked"
    blocked.write_text("this is a file, so .relian cannot be a directory under it")
    with pytest.raises(SigningError, match="Relian emits NO report"):
        load_or_create_instance_key(blocked)


# --------------------------------------------------------------------------
# The CLI refuses to write an unsigned report
# --------------------------------------------------------------------------


def test_the_cli_writes_nothing_when_a_key_cannot_be_obtained(tmp_path) -> None:
    """Acceptance: the failure path is proven by planted-red, not asserted in
    prose. An unsigned artifact that looks signed is worse than no artifact."""
    home = tmp_path / "home"
    home.write_text("not a directory")
    out = tmp_path / "out"
    proc = subprocess.run(
        [sys.executable, "-m", "src.discovery.cli", "report", "build", str(DEMO),
         "--out", str(out), "--customer", "C", "--engagement", "E",
         "--contract-vehicle", "V", "--home", str(home)],
        cwd=str(REPO_ROOT), capture_output=True, text=True, timeout=300,
    )
    assert proc.returncode == 2, proc.stdout + proc.stderr
    assert "REFUSED" in proc.stderr
    assert "No report was written" in proc.stderr
    assert not out.exists(), "a report directory was created despite the refusal"


def test_the_cli_emits_all_three_artifacts_and_names_the_unattested_state(tmp_path) -> None:
    out, _home = _run_build(tmp_path)
    assert (out / "report.json").is_file()
    assert (out / "report.md").is_file()
    assert (out / "report.manifest.json").is_file()


def _run_build(tmp_path, root: Path = DEMO, extra=()):
    home = tmp_path / "home"
    home.mkdir(exist_ok=True)
    out = tmp_path / "out"
    proc = subprocess.run(
        [sys.executable, "-m", "src.discovery.cli", "report", "build", str(root),
         "--out", str(out), "--customer", "Test Agency",
         "--engagement", "Data Discovery", "--contract-vehicle", "TEST-001",
         "--root-label", "examples/demo", "--home", str(home), *extra],
        cwd=str(REPO_ROOT), capture_output=True, text=True, timeout=300,
    )
    assert proc.returncode == 0, proc.stdout + proc.stderr
    return out, home


def test_the_cli_says_valid_and_unattested_before_any_countersignature(tmp_path) -> None:
    home = tmp_path / "home"
    home.mkdir()
    out = tmp_path / "out"
    proc = subprocess.run(
        [sys.executable, "-m", "src.discovery.cli", "report", "build", str(DEMO),
         "--out", str(out), "--customer", "C", "--engagement", "E",
         "--contract-vehicle", "V", "--home", str(home)],
        cwd=str(REPO_ROOT), capture_output=True, text=True, timeout=300,
    )
    assert proc.returncode == 0, proc.stderr
    assert "VALID AND UNATTESTED" in proc.stdout
    assert "Visionblox has not attested to this report" in proc.stdout


# --------------------------------------------------------------------------
# The manifest
# --------------------------------------------------------------------------


@pytest.fixture()
def signed(tmp_path):
    from src.discovery.copybook import resolve
    from src.discovery.layout import compute

    key = load_or_create_instance_key(tmp_path)
    resolution = resolve(DEMO)
    layouts = [
        layout for layout in (compute(n, resolution) for n in sorted(resolution.records))
        if layout is not None
    ]
    report = Report.build(
        resolution, layouts,
        ReportMeta("C", "E", "V", "0.1.0-test", "examples/demo"),
        repo_root=REPO_ROOT,
        instance_fingerprint=key.fingerprint,
        instance_public_key_hex=key.public_key_hex,
    )
    manifest = build_manifest(
        report,
        files=[("report.json", report.to_canonical_json())],
        tool_digests=tool_digests(REPO_ROOT),
        input_digest_rows=input_digests(resolution.records),
        instance=key,
        relian_version="0.1.0-test",
        python_version="3.11.0",
    )
    return report, sign_manifest(manifest, key), key


def test_the_manifest_records_digests_of_inputs_and_never_their_content(signed) -> None:
    """R12. The manifest is what the crossing hash is derived from, so its
    contents must be digests rather than the customer's code."""
    _report, manifest, _key = signed
    assert manifest["input_digests"], "no input digest was recorded at all"
    for row in manifest["input_digests"]:
        assert set(row) == {"name", "path", "sha256"}
        assert len(row["sha256"]) == 64
    blob = manifest_bytes(manifest).decode("utf-8")
    for marker in ("PIC ", "IDENTIFICATION DIVISION", "WORKING-STORAGE"):
        assert marker not in blob, f"the manifest carries source text: {marker!r}"


def test_the_manifest_carries_the_one_timestamp_in_the_deliverable(signed) -> None:
    _report, manifest, _key = signed
    assert manifest["generated_at"].endswith("+00:00")


def test_the_manifest_hash_excludes_the_signature_block(signed) -> None:
    _report, manifest, _key = signed
    without = {k: v for k, v in manifest.items() if k != "signature"}
    assert manifest_hash(manifest) == manifest_hash(without)
    assert manifest["signature"]["manifest_sha256"] == manifest_hash(manifest)


def test_editing_the_manifest_changes_its_hash(signed) -> None:
    _report, manifest, _key = signed
    before = manifest_hash(manifest)
    tampered = json.loads(json.dumps(manifest))
    tampered["files"][0]["sha256"] = "0" * 64
    assert manifest_hash(tampered) != before


def test_the_instance_signature_verifies_over_the_manifest_hash(signed) -> None:
    from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey

    _report, manifest, _key = signed
    block = manifest["signature"]
    Ed25519PublicKey.from_public_bytes(
        bytes.fromhex(block["public_key_hex"])
    ).verify(bytes.fromhex(block["signature_hex"]),
             block["manifest_sha256"].encode("utf-8"))


def test_the_manifest_names_the_signed_artifact_and_the_derived_ones(signed) -> None:
    _report, manifest, _key = signed
    assert manifest["signed_artifact"] == "report.json"
    assert manifest["derived_unsigned_artifacts"] == ["report.md"]


# --------------------------------------------------------------------------
# tools/countersign.py — three refusals, each proven
# --------------------------------------------------------------------------


def _countersign(args, cwd: Path):
    return subprocess.run(
        [sys.executable, str(COUNTERSIGN), *args],
        cwd=str(cwd), capture_output=True, text=True, timeout=120,
    )


def test_countersign_produces_a_detached_signature_over_the_manifest_hash(
    signed, tmp_path
) -> None:
    _report, manifest, _key = signed
    key_path = _ed25519_pem(tmp_path)
    out = tmp_path / "report.countersig.json"
    proc = _countersign(
        ["--manifest-hash", manifest["signature"]["manifest_sha256"],
         "--report-id", manifest["report_id"],
         "--instance-fingerprint", manifest["signature"]["key_fingerprint"],
         "--key", str(key_path), "--out", str(out),
         "--expect-key-fingerprint", _fingerprint_of_pem(key_path)],
        REPO_ROOT,
    )
    assert proc.returncode == 0, proc.stderr
    block = json.loads(out.read_text(encoding="utf-8"))
    assert block["manifest_sha256"] == manifest["signature"]["manifest_sha256"]
    assert block["key_fingerprint"] == _fingerprint_of_pem(key_path)


def test_countersign_fails_hard_on_an_absent_key_with_no_generation_fallback(
    tmp_path,
) -> None:
    """Acceptance ⑨, planted-red. This is the WP-2.1 defect, refused here."""
    absent = tmp_path / "nowhere" / "relian-release.pem"
    out = tmp_path / "report.countersig.json"
    proc = _countersign(
        ["--manifest-hash", "a" * 64, "--report-id", "b" * 32,
         "--instance-fingerprint", "c" * 16, "--key", str(absent), "--out", str(out)],
        REPO_ROOT,
    )
    assert proc.returncode == 2
    assert "NEVER generates a key" in proc.stderr
    assert not absent.exists(), "a key was generated at the absent path"
    assert not out.exists(), "a countersignature was written despite the refusal"


@pytest.mark.parametrize(
    "bad_hash",
    # The last case is the realistic one: a hash transcribed by a human
    # between two machines, broken by a space in the middle. Surrounding
    # whitespace IS stripped -- that is transcription, not corruption -- and
    # the case below proves the strip does not extend to an interior space.
    ["a" * 63, "a" * 65, "", "not-hexadecimal-" + "a" * 48,
     "a" * 32 + " " + "a" * 31],
    ids=["short", "long", "empty", "non-hex", "interior-space"],
)
def test_countersign_refuses_a_hash_that_is_not_64_hex_characters(
    tmp_path, bad_hash: str
) -> None:
    key_path = _ed25519_pem(tmp_path)
    out = tmp_path / "report.countersig.json"
    proc = _countersign(
        ["--manifest-hash", bad_hash, "--report-id", "b" * 32,
         "--instance-fingerprint", "c" * 16, "--key", str(key_path),
         "--out", str(out),
         "--expect-key-fingerprint", _fingerprint_of_pem(key_path)],
        REPO_ROOT,
    )
    assert proc.returncode == 2, proc.stdout
    assert "exactly 64 hexadecimal characters" in proc.stderr
    assert not out.exists()


def test_countersign_accepts_a_hash_with_surrounding_whitespace(tmp_path) -> None:
    """The converse control for the case above: a line copied out of a mail
    client arrives with a newline on it, and that is transcription rather than
    corruption. Stripping it is correct; stripping an interior space is not."""
    key_path = _ed25519_pem(tmp_path)
    out = tmp_path / "cs.json"
    proc = _countersign(
        ["--manifest-hash", "  " + "a" * 64 + "\n", "--report-id", "b" * 32,
         "--instance-fingerprint", "c" * 16, "--key", str(key_path),
         "--out", str(out),
         "--expect-key-fingerprint", _fingerprint_of_pem(key_path)],
        REPO_ROOT,
    )
    assert proc.returncode == 0, proc.stderr
    assert json.loads(out.read_text(encoding="utf-8"))["manifest_sha256"] == "a" * 64


def test_countersign_refuses_a_non_hexadecimal_report_id(tmp_path) -> None:
    """A non-hex field means something other than a digest crossed the
    perimeter. That is R12 failing and it escalates rather than being signed."""
    key_path = _ed25519_pem(tmp_path)
    proc = _countersign(
        ["--manifest-hash", "a" * 64, "--report-id", "MontanaDOR",
         "--instance-fingerprint", "c" * 16, "--key", str(key_path),
         "--out", str(tmp_path / "cs.json"),
         "--expect-key-fingerprint", _fingerprint_of_pem(key_path)],
        REPO_ROOT,
    )
    assert proc.returncode == 2
    assert "R12 failing" in proc.stderr


def test_countersign_refuses_a_key_whose_fingerprint_is_not_the_expected_one(
    tmp_path,
) -> None:
    key_path = _ed25519_pem(tmp_path)
    proc = _countersign(
        ["--manifest-hash", "a" * 64, "--report-id", "b" * 32,
         "--instance-fingerprint", "c" * 16, "--key", str(key_path),
         "--out", str(tmp_path / "cs.json")],           # default: release key
        REPO_ROOT,
    )
    assert proc.returncode == 2
    assert RELEASE_KEY_FINGERPRINT in proc.stderr
    assert "wrong key file" in proc.stderr


def test_the_release_and_bench_fingerprints_are_different_keys() -> None:
    """D23. Reports and benchmarks are different claim classes, so a report-key
    rotation must never put a sealed benchmark in question."""
    assert RELEASE_KEY_FINGERPRINT != BENCH_KEY_FINGERPRINT


def test_countersign_names_the_bench_key_as_forbidden_for_reports() -> None:
    """The bench fingerprint is refused unconditionally, and the refusal is
    reachable from the tool's own source rather than only from this suite."""
    source = COUNTERSIGN.read_text(encoding="utf-8")
    assert BENCH_KEY_FINGERPRINT in source
    assert "must not share a signer" in source


def test_countersign_refuses_the_bench_key_by_fingerprint(tmp_path, monkeypatch) -> None:
    """Planted-red for D23: a key that FINGERPRINTS as the bench key is refused
    even when the caller says it expects that fingerprint."""
    key_path = _ed25519_pem(tmp_path)
    real_fp = _fingerprint_of_pem(key_path)
    sys.path.insert(0, str(REPO_ROOT / "tools"))
    try:
        import countersign as tool

        monkeypatch.setattr(tool, "BENCH_KEY_FINGERPRINT", real_fp)
        with pytest.raises(tool.CountersignError, match="BENCHMARK signing key"):
            tool.countersign(
                "a" * 64, report_id="b" * 32, instance_fingerprint="c" * 16,
                key_path=key_path, expect_fingerprint=real_fp,
            )
    finally:
        sys.path.remove(str(REPO_ROOT / "tools"))
